In [3]:
import numpy as np

## Exercise 1 : Array Creation and Manipulation

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 2 : Type Conversion and Array Operations

In [5]:
arr = np.array([3.14, 2.17, 0, 1, 2]).astype(int)
arr

array([3, 2, 0, 1, 2])

## Exercise 3 : Working with Multi-Dimensional Arrays

In [6]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [7]:
arr = np.random.rand(4, 5).round(2)
arr

array([[0.72, 0.76, 0.51, 0.78, 0.6 ],
       [0.77, 0.32, 0.17, 0.9 , 0.85],
       [0.99, 0.47, 0.7 , 0.68, 0.78],
       [0.8 , 0.08, 0.65, 0.24, 0.41]])

## Exercise 5 : Indexing Arrays

In [10]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1]

array([20, 21, 22, 23, 24])

## Exercise 6 : Reversing elements

In [11]:
arr = np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Exercise 7 : Identity Matrix

In [12]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Exercise 8 : Simple Aggregate Funcs

In [13]:
arr = np.arange(10)
print(f"Sum: {arr.sum()}, Average: {arr.mean()}")

Sum: 45, Average: 4.5


## Exercise 9 : Create Array and Change its Structure

In [14]:
arr = np.arange(1, 21).reshape(4, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Exercise 10 : Conditional Selection of Values

In [17]:
arr = np.arange(10)
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])